# Generated by Django 5.2.7 on 2025-10-22 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Humanet', '0002_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='tipo_organizador',
        ),
    ]
