# Generated by Django 5.1.1 on 2025-10-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humanet', '0003_remove_evento_tipo_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_cuenta',
            field=models.CharField(choices=[('individuo', 'Individuo'), ('organizacion', 'Organización')], default='individuo', max_length=20),
        ),
    ]
