# Generated by Django 5.1.1 on 2025-10-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humanet', '0006_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(default='📌', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#667eea', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='onboarding_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='categorias',
            field=models.ManyToManyField(related_name='eventos', to='Humanet.categoria'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='preferencias',
            field=models.ManyToManyField(blank=True, related_name='usuarios_interesados', to='Humanet.categoria'),
        ),
    ]
