# Generated by Django 5.1.1 on 2025-10-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humanet', '0007_categoria_perfilusuario_onboarding_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='region',
            field=models.CharField(blank=True, choices=[('tarapaca', 'Tarapacá'), ('antofagasta', 'Antofagasta'), ('atacama', 'Atacama'), ('coquimbo', 'Coquimbo'), ('valparaiso', 'Valparaíso'), ('ohiggins', "O'Higgins"), ('maule', 'Maule'), ('nuble', 'Ñuble'), ('biobio', 'Biobío'), ('araucania', 'La Araucanía'), ('los_rios', 'Los Ríos'), ('los_lagos', 'Los Lagos'), ('aysen', 'Aysén'), ('magallanes', 'Magallanes'), ('metropolitana', 'Metropolitana'), ('arica', 'Arica y Parinacota')], max_length=50, null=True),
        ),
    ]
